USE booking_trip;

INSERT IGNORE INTO `role` (`name`) VALUES
                                ('ROLE_ADMIN'),
                                ('ROLE_USER'),
                                ('ROLE_OWNER'),
                                ('ROLE_SHIPPER');
INSERT IGNORE INTO booking_trip.account (id, address, avatar, district, email, firstname, lastname, password, phone, province, status, username, wallet, ward, role_id) VALUES (1, '123 Đường ABC', 'https://chupanhthe.vn/img/lam-sao-de-chup-anh-the-dep1.jpg', 'Quận 1', 'admin1@example.com', 'Nguyen', 'Admin', '123', '0901234567', 'TP.HCM', 'Đang hoạt động', 'adminuser1', 1000000, 'Phường Bến Nghé', 1);
INSERT IGNORE INTO booking_trip.account (id, address, avatar, district, email, firstname, lastname, password, phone, province, status, username, wallet, ward, role_id) VALUES (2, '123 Đường ABC', 'https://chupanhthedanang.com/wp-content/uploads/2021/02/chup-anh-the-da-nang-1.jpg', 'Quận 1', 'admin2@example.com', 'Nguyen', 'Admin', '123', '0901234567', 'TP.HCM', 'Đang hoạt động', 'adminuser2', 1000000, 'Phường Bến Nghé', 1);
INSERT IGNORE INTO booking_trip.account (id, address, avatar, district, email, firstname, lastname, password, phone, province, status, username, wallet, ward, role_id) VALUES (3, '123 Đường ABC', 'https://bizweb.dktcdn.net/100/520/774/products/mau-thay-ao-so-my.jpg?v=1746957444447', 'Quận 1', 'admin3@example.com', 'Nguyen', 'Admin', '123', '0901234567', 'TP.HCM', 'Đang hoạt động', 'adminuser3', 1000000, 'Phường Bến Nghé', 1);
INSERT IGNORE INTO booking_trip.account (id, address, avatar, district, email, firstname, lastname, password, phone, province, status, username, wallet, ward, role_id) VALUES (4, '123 Đường ABC', 'https://toplist.vn/images/800px/tiem-anh-the-kami-1334301.jpg', 'Quận 1', 'admin4@example.com', 'Nguyen', 'Admin', '123', '0901234567', 'TP.HCM', 'Đang hoạt động', 'adminuser4', 1000000, 'Phường Bến Nghé', 1);
INSERT IGNORE INTO booking_trip.account (id, address, avatar, district, email, firstname, lastname, password, phone, province, status, username, wallet, ward, role_id) VALUES (5, '789 Đường QWE', 'https://chupanhthe.vn/img/lam-sao-de-chup-anh-the-dep1.jpg', 'Quận Ngũ Hành Sơn', 'dinhquangduy2002@gmail.com', 'Le', 'Owner1', '123', '0923456789', 'Đà Nẵng', 'Đang hoạt động', 'owner1', 2000000, 'Phường Mỹ An', 3);

INSERT IGNORE INTO booking_trip.owner (id, address, avatar, backside, district, email, firstname, frontside, lastname, phone, province, status, ward, account_id) VALUES (5, '789 Đường QWE', 'https://chupanhthe.vn/img/lam-sao-de-chup-anh-the-dep1.jpg', 'https://cdn.thuvienphapluat.vn/uploads/tintuc/2023/12/16/can-cuoc-cong-dan-2-mat.jpg', 'Quận Ngũ Hành Sơn', 'owner1@example.com', 'Le', 'https://media.vov.vn/sites/default/files/styles/large/public/2021-10/Can%20cuoc.jpg', 'Owner1', '0923456789', 'Đà Nẵng', 'VERIFIED', 'Phường Mỹ An', 5);

INSERT IGNORE INTO `category` (`name`) VALUES
                                    ('Luxury'),
                                    ('Thường');

INSERT IGNORE INTO booking_trip.trip (id, address, area, create_at, departure, description, destination, driver, license_plate, name, price, sale, seat, seat_booking, status, thumbnail, update_at, category_id, owner_id, departure_date) VALUES (10, '22, Phường Xuân Phương, Quận Nam Từ Liêm, Hà Nội', 10, '2025-06-22', 'Hà Nội', '<p><strong>Du lịch Quảng Ninh</strong>&nbsp;c&oacute; v&ocirc; v&agrave;n địa điểm đẹp v&agrave; nổi tiếng thu h&uacute;t du kh&aacute;ch bốn phương. Kh&ocirc;ng chỉ c&oacute; vậy, Quảng Ninh c&ograve;n khiến du kh&aacute;ch ngất ng&acirc;y&nbsp;với&nbsp;những đặc sản ngon kh&oacute; cưỡng. Nếu bạn cũng đang c&oacute; dự định đến đ&acirc;y trong thời gian tới th&igrave; h&atilde;y lưu lại ngay c&aacute;c th&ocirc;ng tin ở b&agrave;i viết sau đ&acirc;y nh&eacute;!</p>
<p><img src="https://statics.vinpearl.com/du-lich-Quang-Ninh-hinh-anh1.jpg" alt="du lich quang ninh hinh anh 1" data-align="center" data-caption="Vịnh Hạ Long Quảng Ninh (Nguồn: B&aacute;o Ch&iacute;nh phủ)" data-entity-type="file" data-entity-uuid="5c5e6c07-6294-49a8-97ad-0707ef6dabe5"><em class="img_caption">Vịnh Hạ Long Quảng Ninh (Nguồn: B&aacute;o Ch&iacute;nh phủ)</em></p>
<h2 id="1.+Giới+thiệu+về+du+lịch+Quảng+Ninh+-+V&ugrave;ng+đất+di+sản">1. Giới thiệu về du lịch Quảng Ninh - V&ugrave;ng đất di sản</h2>
<p>Quảng Ninh thuộc v&ugrave;ng Đ&ocirc;ng Bắc Việt Nam. Nơi đ&acirc;y hấp dẫn bởi vẻ đẹp kỳ th&uacute; của n&uacute;i non, s&ocirc;ng nước v&agrave; biển đảo. Nổi bật hơn cả ch&iacute;nh l&agrave;&nbsp;<strong>vịnh Hạ Long - Di sản thi&ecirc;n nhi&ecirc;n thế giới được UNESCO c&ocirc;ng nhận</strong>. Đến với Hạ Long, du kh&aacute;ch sẽ c&oacute; cơ hội chi&ecirc;m ngưỡng bức tranh non nước v&ocirc; c&ugrave;ng ngoạn mục được tạo th&agrave;nh bởi 1.900 h&ograve;n đ&aacute; v&ocirc;i kh&aacute;c nhau c&ugrave;ng nhiều hang động kỳ b&iacute;.</p>
<p>Chưa dừng lại ở đ&oacute;, Quảng Ninh c&ograve;n l&agrave; mảnh đất sở hữu 2 c&ocirc;ng vi&ecirc;n giải tr&iacute; lớn nhất khu vực Đ&ocirc;ng Nam &Aacute; l&agrave; Typhoon Water Park v&agrave; Dragon Park. Tại hai c&ocirc;ng vi&ecirc;n n&agrave;y, c&oacute; rất nhiều những trải nghiệm th&uacute; vị đang chờ đợi du kh&aacute;ch như t&agrave;u lượn si&ecirc;u tốc 1,1km d&agrave;i nhất Ch&acirc;u &Aacute; v&agrave; hơn 12 tr&ograve; chơi dưới nước d&agrave;nh cho mọi lứa tuổi.</p>
<p><img src="https://statics.vinpearl.com/du-lich-Quang-Ninh-hinh-anh2.jpg" alt="du lich quang ninh hinh anh 2" data-align="center" data-caption="Sống ảo khi đi du lịch Quảng Ninh (Nguồn: Vietnammoi)" data-entity-type="file" data-entity-uuid="51e13db7-fb53-4e61-ba2b-624e0038d11c"><em class="img_caption">Sống ảo khi đi du lịch Quảng Ninh (Nguồn: Vietnammoi)</em></p>
<div class="sku-item checked">
<div class="hotel-wrapper promo-wrapper hotel-api">
<div class="hotel-img-wrapper">
<div id="carousel-bacc" class="carousel slide" data-ride="carousel" data-interval="false">
<div class="carousel-inner">
<div class="carousel-item active"><img class="w-100" src="https://booking-static.vinpearl.com/hotels/004a48b7f5de44638f267d5e085f20e8_VPRSHL%20Facade11.jpg" alt="anh khong gian phong" data-src="https://booking-static.vinpearl.com/hotels/004a48b7f5de44638f267d5e085f20e8_VPRSHL Facade11.jpg"></div>
</div>
</div>
</div>
</div>
</div>
<h2 id="2.+N&ecirc;n+đi+du+lịch+ở+Quảng+Ninh+v&agrave;o+thời+gian+n&agrave;o?">2. N&ecirc;n đi du lịch ở Quảng Ninh v&agrave;o thời gian n&agrave;o?</h2>
<p>Quảng Ninh c&oacute; 4 m&ugrave;a r&otilde; rệt trong năm, kiểu thời tiết điển h&igrave;nh của những tỉnh th&agrave;nh ph&iacute;a Bắc. Tuy nhi&ecirc;n, nơi đ&acirc;y cũng c&oacute; những n&eacute;t ri&ecirc;ng của một tỉnh miền n&uacute;i ven biển. Cụ thể, ở khu vực quần đảo thuộc huyện V&acirc;n Đồn, C&ocirc; T&ocirc;... thời tiết sẽ c&oacute; ch&uacute;t kh&aacute;c biệt. Hơn nữa, Quảng Ninh cũng nằm trong v&ugrave;ng kh&iacute; hậu nhiệt đới n&ecirc;n m&ugrave;a hạ sẽ n&oacute;ng ẩm mưa nhiều, c&ograve;n m&ugrave;a đ&ocirc;ng sẽ lạnh v&agrave; &iacute;t mưa.</p>
<p>Theo kinh nghiệm du lịch Quảng Ninh của nhiều du kh&aacute;ch th&igrave; khoảng từ&nbsp;<strong>cuối th&aacute;ng 4 đến th&aacute;ng 9</strong>&nbsp;ch&iacute;nh l&agrave; thời điểm đẹp nhất để du lịch Quảng Ninh bởi l&uacute;c n&agrave;y biển đẹp, trong xanh, thời tiết m&aacute;t mẻ, trong l&agrave;nh, dễ chịu. Đ&acirc;y cũng l&agrave; khoảng thời gian ở Quảng Ninh diễn ra nhiều hoạt động văn h&oacute;a nổi bật như Tuần lễ du lịch Hạ Long - Quảng Ninh, &acirc;m nhạc m&ugrave;a h&egrave;, lễ hội Y&ecirc;n Tử...</p>
<p><img src="https://statics.vinpearl.com/du-lich-Quang-Ninh-hinh-anh3.jpg" alt="du lich quang ninh hinh anh 3" data-align="center" data-caption="Vịnh Hạ Long từ tr&ecirc;n cao (Nguồn: Foody)" data-entity-type="file" data-entity-uuid="74bd77f7-0b82-4373-b694-c2f110abf100"><em class="img_caption">Vịnh Hạ Long từ tr&ecirc;n cao (Nguồn: Foody)</em></p>', 'Quảng Ninh', '<p>Nguyễn Văn B</p>', '29k-99999', 'Chuyến Hà Nội - Quảng Ninh', 300000, 0, 5, 0, 'Sắp khởi hành', 'https://firebasestorage.googleapis.com/v0/b/fir-15eec.appspot.com/o/images%2Fmec.jpeg47aa019c-3631-4b8b-a583-61d33b363bd0?alt=media&token=74d6ae1b-076a-4e9e-8d2c-0db9a4cd0944', '2025-06-22', 2, 5, '2025-06-29');
INSERT IGNORE INTO booking_trip.trip (id, address, area, create_at, departure, description, destination, driver, license_plate, name, price, sale, seat, seat_booking, status, thumbnail, update_at, category_id, owner_id, departure_date) VALUES (1, 'số 21, Xã Vũ Oai, Huyện Hoành Bồ, Quảng Ninh', 40, '2025-06-30', 'Quảng Ninh', '<p><strong>Du lịch Quảng Ninh</strong>&nbsp;c&oacute; v&ocirc; v&agrave;n địa điểm đẹp v&agrave; nổi tiếng thu h&uacute;t du kh&aacute;ch bốn phương. Kh&ocirc;ng chỉ c&oacute; vậy, Quảng Ninh c&ograve;n khiến du kh&aacute;ch ngất ng&acirc;y&nbsp;với&nbsp;những đặc sản ngon kh&oacute; cưỡng. Nếu bạn cũng đang c&oacute; dự định đến đ&acirc;y trong thời gian tới th&igrave; h&atilde;y lưu lại ngay c&aacute;c th&ocirc;ng tin ở b&agrave;i viết sau đ&acirc;y nh&eacute;!</p>
<p><img src="https://statics.vinpearl.com/du-lich-Quang-Ninh-hinh-anh1.jpg" alt="du lich quang ninh hinh anh 1" data-align="center" data-caption="Vịnh Hạ Long Quảng Ninh (Nguồn: B&aacute;o Ch&iacute;nh phủ)" data-entity-type="file" data-entity-uuid="5c5e6c07-6294-49a8-97ad-0707ef6dabe5"><em class="img_caption">Vịnh Hạ Long Quảng Ninh (Nguồn: B&aacute;o Ch&iacute;nh phủ)</em></p>
<h2 id="1.+Giới+thiệu+về+du+lịch+Quảng+Ninh+-+V&ugrave;ng+đất+di+sản">1. Giới thiệu về du lịch Quảng Ninh - V&ugrave;ng đất di sản</h2>
<p>Quảng Ninh thuộc v&ugrave;ng Đ&ocirc;ng Bắc Việt Nam. Nơi đ&acirc;y hấp dẫn bởi vẻ đẹp kỳ th&uacute; của n&uacute;i non, s&ocirc;ng nước v&agrave; biển đảo. Nổi bật hơn cả ch&iacute;nh l&agrave;&nbsp;<strong>vịnh Hạ Long - Di sản thi&ecirc;n nhi&ecirc;n thế giới được UNESCO c&ocirc;ng nhận</strong>. Đến với Hạ Long, du kh&aacute;ch sẽ c&oacute; cơ hội chi&ecirc;m ngưỡng bức tranh non nước v&ocirc; c&ugrave;ng ngoạn mục được tạo th&agrave;nh bởi 1.900 h&ograve;n đ&aacute; v&ocirc;i kh&aacute;c nhau c&ugrave;ng nhiều hang động kỳ b&iacute;.</p>
<p>Chưa dừng lại ở đ&oacute;, Quảng Ninh c&ograve;n l&agrave; mảnh đất sở hữu 2 c&ocirc;ng vi&ecirc;n giải tr&iacute; lớn nhất khu vực Đ&ocirc;ng Nam &Aacute; l&agrave; Typhoon Water Park v&agrave; Dragon Park. Tại hai c&ocirc;ng vi&ecirc;n n&agrave;y, c&oacute; rất nhiều những trải nghiệm th&uacute; vị đang chờ đợi du kh&aacute;ch như t&agrave;u lượn si&ecirc;u tốc 1,1km d&agrave;i nhất Ch&acirc;u &Aacute; v&agrave; hơn 12 tr&ograve; chơi dưới nước d&agrave;nh cho mọi lứa tuổi.</p>
<p><img src="https://statics.vinpearl.com/du-lich-Quang-Ninh-hinh-anh2.jpg" alt="du lich quang ninh hinh anh 2" data-align="center" data-caption="Sống ảo khi đi du lịch Quảng Ninh (Nguồn: Vietnammoi)" data-entity-type="file" data-entity-uuid="51e13db7-fb53-4e61-ba2b-624e0038d11c"><em class="img_caption">Sống ảo khi đi du lịch Quảng Ninh (Nguồn: Vietnammoi)</em></p>
<div class="sku-item checked">
<div class="hotel-wrapper promo-wrapper hotel-api">
<div class="hotel-img-wrapper">
<div id="carousel-bacc" class="carousel slide" data-ride="carousel" data-interval="false">
<div class="carousel-inner">
<div class="carousel-item active"><img class="w-100" src="https://booking-static.vinpearl.com/hotels/004a48b7f5de44638f267d5e085f20e8_VPRSHL%20Facade11.jpg" alt="anh khong gian phong" data-src="https://booking-static.vinpearl.com/hotels/004a48b7f5de44638f267d5e085f20e8_VPRSHL Facade11.jpg"></div>
</div>
</div>
</div>
</div>
</div>
<h2 id="2.+N&ecirc;n+đi+du+lịch+ở+Quảng+Ninh+v&agrave;o+thời+gian+n&agrave;o?">2. N&ecirc;n đi du lịch ở Quảng Ninh v&agrave;o thời gian n&agrave;o?</h2>
<p>Quảng Ninh c&oacute; 4 m&ugrave;a r&otilde; rệt trong năm, kiểu thời tiết điển h&igrave;nh của những tỉnh th&agrave;nh ph&iacute;a Bắc. Tuy nhi&ecirc;n, nơi đ&acirc;y cũng c&oacute; những n&eacute;t ri&ecirc;ng của một tỉnh miền n&uacute;i ven biển. Cụ thể, ở khu vực quần đảo thuộc huyện V&acirc;n Đồn, C&ocirc; T&ocirc;... thời tiết sẽ c&oacute; ch&uacute;t kh&aacute;c biệt. Hơn nữa, Quảng Ninh cũng nằm trong v&ugrave;ng kh&iacute; hậu nhiệt đới n&ecirc;n m&ugrave;a hạ sẽ n&oacute;ng ẩm mưa nhiều, c&ograve;n m&ugrave;a đ&ocirc;ng sẽ lạnh v&agrave; &iacute;t mưa.</p>
<p>Theo kinh nghiệm du lịch Quảng Ninh của nhiều du kh&aacute;ch th&igrave; khoảng từ&nbsp;<strong>cuối th&aacute;ng 4 đến th&aacute;ng 9</strong>&nbsp;ch&iacute;nh l&agrave; thời điểm đẹp nhất để du lịch Quảng Ninh bởi l&uacute;c n&agrave;y biển đẹp, trong xanh, thời tiết m&aacute;t mẻ, trong l&agrave;nh, dễ chịu. Đ&acirc;y cũng l&agrave; khoảng thời gian ở Quảng Ninh diễn ra nhiều hoạt động văn h&oacute;a nổi bật như Tuần lễ du lịch Hạ Long - Quảng Ninh, &acirc;m nhạc m&ugrave;a h&egrave;, lễ hội Y&ecirc;n Tử...</p>
<p><img src="https://statics.vinpearl.com/du-lich-Quang-Ninh-hinh-anh3.jpg" alt="du lich quang ninh hinh anh 3" data-align="center" data-caption="Vịnh Hạ Long từ tr&ecirc;n cao (Nguồn: Foody)" data-entity-type="file" data-entity-uuid="74bd77f7-0b82-4373-b694-c2f110abf100"><em class="img_caption">Vịnh Hạ Long từ tr&ecirc;n cao (Nguồn: Foody)</em></p>', 'Hà Nội', 'Nguyễn Văn A', '14A1-99999', 'Chuyến Hạ Long - Hà Nội', 200000, 10, 16, 10, 'Sắp khởi hành', 'https://thanhxuanford.vn/public/upload/images/hinhsanpham/ford-transit-premium-16-cho-83201720171105.png', '2025-06-18', 1, 5, '2025-06-30');
INSERT IGNORE INTO booking_trip.trip (id, address, area, create_at, departure, description, destination, driver, license_plate, name, price, sale, seat, seat_booking, status, thumbnail, update_at, category_id, owner_id, departure_date) VALUES (2, 'số 21, Xã Vũ Oai, Huyện Hoành Bồ, Quảng Ninh', 40, '2025-06-30', 'Quảng Ninh', '<p><strong>Du lịch Quảng Ninh</strong>&nbsp;c&oacute; v&ocirc; v&agrave;n địa điểm đẹp v&agrave; nổi tiếng thu h&uacute;t du kh&aacute;ch bốn phương. Kh&ocirc;ng chỉ c&oacute; vậy, Quảng Ninh c&ograve;n khiến du kh&aacute;ch ngất ng&acirc;y&nbsp;với&nbsp;những đặc sản ngon kh&oacute; cưỡng. Nếu bạn cũng đang c&oacute; dự định đến đ&acirc;y trong thời gian tới th&igrave; h&atilde;y lưu lại ngay c&aacute;c th&ocirc;ng tin ở b&agrave;i viết sau đ&acirc;y nh&eacute;!</p>
<p><img src="https://statics.vinpearl.com/du-lich-Quang-Ninh-hinh-anh1.jpg" alt="du lich quang ninh hinh anh 1" data-align="center" data-caption="Vịnh Hạ Long Quảng Ninh (Nguồn: B&aacute;o Ch&iacute;nh phủ)" data-entity-type="file" data-entity-uuid="5c5e6c07-6294-49a8-97ad-0707ef6dabe5"><em class="img_caption">Vịnh Hạ Long Quảng Ninh (Nguồn: B&aacute;o Ch&iacute;nh phủ)</em></p>
<h2 id="1.+Giới+thiệu+về+du+lịch+Quảng+Ninh+-+V&ugrave;ng+đất+di+sản">1. Giới thiệu về du lịch Quảng Ninh - V&ugrave;ng đất di sản</h2>
<p>Quảng Ninh thuộc v&ugrave;ng Đ&ocirc;ng Bắc Việt Nam. Nơi đ&acirc;y hấp dẫn bởi vẻ đẹp kỳ th&uacute; của n&uacute;i non, s&ocirc;ng nước v&agrave; biển đảo. Nổi bật hơn cả ch&iacute;nh l&agrave;&nbsp;<strong>vịnh Hạ Long - Di sản thi&ecirc;n nhi&ecirc;n thế giới được UNESCO c&ocirc;ng nhận</strong>. Đến với Hạ Long, du kh&aacute;ch sẽ c&oacute; cơ hội chi&ecirc;m ngưỡng bức tranh non nước v&ocirc; c&ugrave;ng ngoạn mục được tạo th&agrave;nh bởi 1.900 h&ograve;n đ&aacute; v&ocirc;i kh&aacute;c nhau c&ugrave;ng nhiều hang động kỳ b&iacute;.</p>
<p>Chưa dừng lại ở đ&oacute;, Quảng Ninh c&ograve;n l&agrave; mảnh đất sở hữu 2 c&ocirc;ng vi&ecirc;n giải tr&iacute; lớn nhất khu vực Đ&ocirc;ng Nam &Aacute; l&agrave; Typhoon Water Park v&agrave; Dragon Park. Tại hai c&ocirc;ng vi&ecirc;n n&agrave;y, c&oacute; rất nhiều những trải nghiệm th&uacute; vị đang chờ đợi du kh&aacute;ch như t&agrave;u lượn si&ecirc;u tốc 1,1km d&agrave;i nhất Ch&acirc;u &Aacute; v&agrave; hơn 12 tr&ograve; chơi dưới nước d&agrave;nh cho mọi lứa tuổi.</p>
<p><img src="https://statics.vinpearl.com/du-lich-Quang-Ninh-hinh-anh2.jpg" alt="du lich quang ninh hinh anh 2" data-align="center" data-caption="Sống ảo khi đi du lịch Quảng Ninh (Nguồn: Vietnammoi)" data-entity-type="file" data-entity-uuid="51e13db7-fb53-4e61-ba2b-624e0038d11c"><em class="img_caption">Sống ảo khi đi du lịch Quảng Ninh (Nguồn: Vietnammoi)</em></p>
<div class="sku-item checked">
<div class="hotel-wrapper promo-wrapper hotel-api">
<div class="hotel-img-wrapper">
<div id="carousel-bacc" class="carousel slide" data-ride="carousel" data-interval="false">
<div class="carousel-inner">
<div class="carousel-item active"><img class="w-100" src="https://booking-static.vinpearl.com/hotels/004a48b7f5de44638f267d5e085f20e8_VPRSHL%20Facade11.jpg" alt="anh khong gian phong" data-src="https://booking-static.vinpearl.com/hotels/004a48b7f5de44638f267d5e085f20e8_VPRSHL Facade11.jpg"></div>
</div>
</div>
</div>
</div>
</div>
<h2 id="2.+N&ecirc;n+đi+du+lịch+ở+Quảng+Ninh+v&agrave;o+thời+gian+n&agrave;o?">2. N&ecirc;n đi du lịch ở Quảng Ninh v&agrave;o thời gian n&agrave;o?</h2>
<p>Quảng Ninh c&oacute; 4 m&ugrave;a r&otilde; rệt trong năm, kiểu thời tiết điển h&igrave;nh của những tỉnh th&agrave;nh ph&iacute;a Bắc. Tuy nhi&ecirc;n, nơi đ&acirc;y cũng c&oacute; những n&eacute;t ri&ecirc;ng của một tỉnh miền n&uacute;i ven biển. Cụ thể, ở khu vực quần đảo thuộc huyện V&acirc;n Đồn, C&ocirc; T&ocirc;... thời tiết sẽ c&oacute; ch&uacute;t kh&aacute;c biệt. Hơn nữa, Quảng Ninh cũng nằm trong v&ugrave;ng kh&iacute; hậu nhiệt đới n&ecirc;n m&ugrave;a hạ sẽ n&oacute;ng ẩm mưa nhiều, c&ograve;n m&ugrave;a đ&ocirc;ng sẽ lạnh v&agrave; &iacute;t mưa.</p>
<p>Theo kinh nghiệm du lịch Quảng Ninh của nhiều du kh&aacute;ch th&igrave; khoảng từ&nbsp;<strong>cuối th&aacute;ng 4 đến th&aacute;ng 9</strong>&nbsp;ch&iacute;nh l&agrave; thời điểm đẹp nhất để du lịch Quảng Ninh bởi l&uacute;c n&agrave;y biển đẹp, trong xanh, thời tiết m&aacute;t mẻ, trong l&agrave;nh, dễ chịu. Đ&acirc;y cũng l&agrave; khoảng thời gian ở Quảng Ninh diễn ra nhiều hoạt động văn h&oacute;a nổi bật như Tuần lễ du lịch Hạ Long - Quảng Ninh, &acirc;m nhạc m&ugrave;a h&egrave;, lễ hội Y&ecirc;n Tử...</p>
<p><img src="https://statics.vinpearl.com/du-lich-Quang-Ninh-hinh-anh3.jpg" alt="du lich quang ninh hinh anh 3" data-align="center" data-caption="Vịnh Hạ Long từ tr&ecirc;n cao (Nguồn: Foody)" data-entity-type="file" data-entity-uuid="74bd77f7-0b82-4373-b694-c2f110abf100"><em class="img_caption">Vịnh Hạ Long từ tr&ecirc;n cao (Nguồn: Foody)</em></p>', 'Hà Nội', 'Nguyễn Văn A', '14A1-99999', 'Chuyến Móng Cái - Hà Nội', 300000, 5, 45, 5, 'Sắp khởi hành', 'https://product.hstatic.net/200000504989/product/cho_thue_xe_45_cho_kia_grandbird-6_c69b77d54ea446768eb7b465b3907146_master.jpg', '2025-06-18', 2, 5, '2025-06-30');
INSERT IGNORE INTO booking_trip.trip (id, address, area, create_at, departure, description, destination, driver, license_plate, name, price, sale, seat, seat_booking, status, thumbnail, update_at, category_id, owner_id, departure_date) VALUES (3, 'số 21, Xã Vũ Oai, Huyện Hoành Bồ, Quảng Ninh', 40, '2025-06-30', 'Quảng Ninh', '<p><strong>Du lịch Quảng Ninh</strong>&nbsp;c&oacute; v&ocirc; v&agrave;n địa điểm đẹp v&agrave; nổi tiếng thu h&uacute;t du kh&aacute;ch bốn phương. Kh&ocirc;ng chỉ c&oacute; vậy, Quảng Ninh c&ograve;n khiến du kh&aacute;ch ngất ng&acirc;y&nbsp;với&nbsp;những đặc sản ngon kh&oacute; cưỡng. Nếu bạn cũng đang c&oacute; dự định đến đ&acirc;y trong thời gian tới th&igrave; h&atilde;y lưu lại ngay c&aacute;c th&ocirc;ng tin ở b&agrave;i viết sau đ&acirc;y nh&eacute;!</p>
<p><img src="https://statics.vinpearl.com/du-lich-Quang-Ninh-hinh-anh1.jpg" alt="du lich quang ninh hinh anh 1" data-align="center" data-caption="Vịnh Hạ Long Quảng Ninh (Nguồn: B&aacute;o Ch&iacute;nh phủ)" data-entity-type="file" data-entity-uuid="5c5e6c07-6294-49a8-97ad-0707ef6dabe5"><em class="img_caption">Vịnh Hạ Long Quảng Ninh (Nguồn: B&aacute;o Ch&iacute;nh phủ)</em></p>
<h2 id="1.+Giới+thiệu+về+du+lịch+Quảng+Ninh+-+V&ugrave;ng+đất+di+sản">1. Giới thiệu về du lịch Quảng Ninh - V&ugrave;ng đất di sản</h2>
<p>Quảng Ninh thuộc v&ugrave;ng Đ&ocirc;ng Bắc Việt Nam. Nơi đ&acirc;y hấp dẫn bởi vẻ đẹp kỳ th&uacute; của n&uacute;i non, s&ocirc;ng nước v&agrave; biển đảo. Nổi bật hơn cả ch&iacute;nh l&agrave;&nbsp;<strong>vịnh Hạ Long - Di sản thi&ecirc;n nhi&ecirc;n thế giới được UNESCO c&ocirc;ng nhận</strong>. Đến với Hạ Long, du kh&aacute;ch sẽ c&oacute; cơ hội chi&ecirc;m ngưỡng bức tranh non nước v&ocirc; c&ugrave;ng ngoạn mục được tạo th&agrave;nh bởi 1.900 h&ograve;n đ&aacute; v&ocirc;i kh&aacute;c nhau c&ugrave;ng nhiều hang động kỳ b&iacute;.</p>
<p>Chưa dừng lại ở đ&oacute;, Quảng Ninh c&ograve;n l&agrave; mảnh đất sở hữu 2 c&ocirc;ng vi&ecirc;n giải tr&iacute; lớn nhất khu vực Đ&ocirc;ng Nam &Aacute; l&agrave; Typhoon Water Park v&agrave; Dragon Park. Tại hai c&ocirc;ng vi&ecirc;n n&agrave;y, c&oacute; rất nhiều những trải nghiệm th&uacute; vị đang chờ đợi du kh&aacute;ch như t&agrave;u lượn si&ecirc;u tốc 1,1km d&agrave;i nhất Ch&acirc;u &Aacute; v&agrave; hơn 12 tr&ograve; chơi dưới nước d&agrave;nh cho mọi lứa tuổi.</p>
<p><img src="https://statics.vinpearl.com/du-lich-Quang-Ninh-hinh-anh2.jpg" alt="du lich quang ninh hinh anh 2" data-align="center" data-caption="Sống ảo khi đi du lịch Quảng Ninh (Nguồn: Vietnammoi)" data-entity-type="file" data-entity-uuid="51e13db7-fb53-4e61-ba2b-624e0038d11c"><em class="img_caption">Sống ảo khi đi du lịch Quảng Ninh (Nguồn: Vietnammoi)</em></p>
<div class="sku-item checked">
<div class="hotel-wrapper promo-wrapper hotel-api">
<div class="hotel-img-wrapper">
<div id="carousel-bacc" class="carousel slide" data-ride="carousel" data-interval="false">
<div class="carousel-inner">
<div class="carousel-item active"><img class="w-100" src="https://booking-static.vinpearl.com/hotels/004a48b7f5de44638f267d5e085f20e8_VPRSHL%20Facade11.jpg" alt="anh khong gian phong" data-src="https://booking-static.vinpearl.com/hotels/004a48b7f5de44638f267d5e085f20e8_VPRSHL Facade11.jpg"></div>
</div>
</div>
</div>
</div>
</div>
<h2 id="2.+N&ecirc;n+đi+du+lịch+ở+Quảng+Ninh+v&agrave;o+thời+gian+n&agrave;o?">2. N&ecirc;n đi du lịch ở Quảng Ninh v&agrave;o thời gian n&agrave;o?</h2>
<p>Quảng Ninh c&oacute; 4 m&ugrave;a r&otilde; rệt trong năm, kiểu thời tiết điển h&igrave;nh của những tỉnh th&agrave;nh ph&iacute;a Bắc. Tuy nhi&ecirc;n, nơi đ&acirc;y cũng c&oacute; những n&eacute;t ri&ecirc;ng của một tỉnh miền n&uacute;i ven biển. Cụ thể, ở khu vực quần đảo thuộc huyện V&acirc;n Đồn, C&ocirc; T&ocirc;... thời tiết sẽ c&oacute; ch&uacute;t kh&aacute;c biệt. Hơn nữa, Quảng Ninh cũng nằm trong v&ugrave;ng kh&iacute; hậu nhiệt đới n&ecirc;n m&ugrave;a hạ sẽ n&oacute;ng ẩm mưa nhiều, c&ograve;n m&ugrave;a đ&ocirc;ng sẽ lạnh v&agrave; &iacute;t mưa.</p>
<p>Theo kinh nghiệm du lịch Quảng Ninh của nhiều du kh&aacute;ch th&igrave; khoảng từ&nbsp;<strong>cuối th&aacute;ng 4 đến th&aacute;ng 9</strong>&nbsp;ch&iacute;nh l&agrave; thời điểm đẹp nhất để du lịch Quảng Ninh bởi l&uacute;c n&agrave;y biển đẹp, trong xanh, thời tiết m&aacute;t mẻ, trong l&agrave;nh, dễ chịu. Đ&acirc;y cũng l&agrave; khoảng thời gian ở Quảng Ninh diễn ra nhiều hoạt động văn h&oacute;a nổi bật như Tuần lễ du lịch Hạ Long - Quảng Ninh, &acirc;m nhạc m&ugrave;a h&egrave;, lễ hội Y&ecirc;n Tử...</p>
<p><img src="https://statics.vinpearl.com/du-lich-Quang-Ninh-hinh-anh3.jpg" alt="du lich quang ninh hinh anh 3" data-align="center" data-caption="Vịnh Hạ Long từ tr&ecirc;n cao (Nguồn: Foody)" data-entity-type="file" data-entity-uuid="74bd77f7-0b82-4373-b694-c2f110abf100"><em class="img_caption">Vịnh Hạ Long từ tr&ecirc;n cao (Nguồn: Foody)</em></p>', 'Hà Nội', 'Nguyễn Văn A', '14A1-99999', 'Chuyến Yên Tử - Hà Nội', 300000, 0, 7, 2, 'Sắp khởi hành', 'https://hyundaingocphat.com.vn/wp-content/uploads/2024/05/xe-hyundai-7-cho-moi-nhat.jpg', '2025-06-18', 2, 5, '2025-06-30');
INSERT IGNORE INTO booking_trip.trip (id, address, area, create_at, departure, description, destination, driver, license_plate, name, price, sale, seat, seat_booking, status, thumbnail, update_at, category_id, owner_id, departure_date) VALUES (4, 'số 21, Xã Vũ Oai, Huyện Hoành Bồ, Quảng Ninh', 40, '2025-06-30', 'Quảng Ninh', '<p><strong>Du lịch Quảng Ninh</strong>&nbsp;c&oacute; v&ocirc; v&agrave;n địa điểm đẹp v&agrave; nổi tiếng thu h&uacute;t du kh&aacute;ch bốn phương. Kh&ocirc;ng chỉ c&oacute; vậy, Quảng Ninh c&ograve;n khiến du kh&aacute;ch ngất ng&acirc;y&nbsp;với&nbsp;những đặc sản ngon kh&oacute; cưỡng. Nếu bạn cũng đang c&oacute; dự định đến đ&acirc;y trong thời gian tới th&igrave; h&atilde;y lưu lại ngay c&aacute;c th&ocirc;ng tin ở b&agrave;i viết sau đ&acirc;y nh&eacute;!</p>
<p><img src="https://statics.vinpearl.com/du-lich-Quang-Ninh-hinh-anh1.jpg" alt="du lich quang ninh hinh anh 1" data-align="center" data-caption="Vịnh Hạ Long Quảng Ninh (Nguồn: B&aacute;o Ch&iacute;nh phủ)" data-entity-type="file" data-entity-uuid="5c5e6c07-6294-49a8-97ad-0707ef6dabe5"><em class="img_caption">Vịnh Hạ Long Quảng Ninh (Nguồn: B&aacute;o Ch&iacute;nh phủ)</em></p>
<h2 id="1.+Giới+thiệu+về+du+lịch+Quảng+Ninh+-+V&ugrave;ng+đất+di+sản">1. Giới thiệu về du lịch Quảng Ninh - V&ugrave;ng đất di sản</h2>
<p>Quảng Ninh thuộc v&ugrave;ng Đ&ocirc;ng Bắc Việt Nam. Nơi đ&acirc;y hấp dẫn bởi vẻ đẹp kỳ th&uacute; của n&uacute;i non, s&ocirc;ng nước v&agrave; biển đảo. Nổi bật hơn cả ch&iacute;nh l&agrave;&nbsp;<strong>vịnh Hạ Long - Di sản thi&ecirc;n nhi&ecirc;n thế giới được UNESCO c&ocirc;ng nhận</strong>. Đến với Hạ Long, du kh&aacute;ch sẽ c&oacute; cơ hội chi&ecirc;m ngưỡng bức tranh non nước v&ocirc; c&ugrave;ng ngoạn mục được tạo th&agrave;nh bởi 1.900 h&ograve;n đ&aacute; v&ocirc;i kh&aacute;c nhau c&ugrave;ng nhiều hang động kỳ b&iacute;.</p>
<p>Chưa dừng lại ở đ&oacute;, Quảng Ninh c&ograve;n l&agrave; mảnh đất sở hữu 2 c&ocirc;ng vi&ecirc;n giải tr&iacute; lớn nhất khu vực Đ&ocirc;ng Nam &Aacute; l&agrave; Typhoon Water Park v&agrave; Dragon Park. Tại hai c&ocirc;ng vi&ecirc;n n&agrave;y, c&oacute; rất nhiều những trải nghiệm th&uacute; vị đang chờ đợi du kh&aacute;ch như t&agrave;u lượn si&ecirc;u tốc 1,1km d&agrave;i nhất Ch&acirc;u &Aacute; v&agrave; hơn 12 tr&ograve; chơi dưới nước d&agrave;nh cho mọi lứa tuổi.</p>
<p><img src="https://statics.vinpearl.com/du-lich-Quang-Ninh-hinh-anh2.jpg" alt="du lich quang ninh hinh anh 2" data-align="center" data-caption="Sống ảo khi đi du lịch Quảng Ninh (Nguồn: Vietnammoi)" data-entity-type="file" data-entity-uuid="51e13db7-fb53-4e61-ba2b-624e0038d11c"><em class="img_caption">Sống ảo khi đi du lịch Quảng Ninh (Nguồn: Vietnammoi)</em></p>
<div class="sku-item checked">
<div class="hotel-wrapper promo-wrapper hotel-api">
<div class="hotel-img-wrapper">
<div id="carousel-bacc" class="carousel slide" data-ride="carousel" data-interval="false">
<div class="carousel-inner">
<div class="carousel-item active"><img class="w-100" src="https://booking-static.vinpearl.com/hotels/004a48b7f5de44638f267d5e085f20e8_VPRSHL%20Facade11.jpg" alt="anh khong gian phong" data-src="https://booking-static.vinpearl.com/hotels/004a48b7f5de44638f267d5e085f20e8_VPRSHL Facade11.jpg"></div>
</div>
</div>
</div>
</div>
</div>
<h2 id="2.+N&ecirc;n+đi+du+lịch+ở+Quảng+Ninh+v&agrave;o+thời+gian+n&agrave;o?">2. N&ecirc;n đi du lịch ở Quảng Ninh v&agrave;o thời gian n&agrave;o?</h2>
<p>Quảng Ninh c&oacute; 4 m&ugrave;a r&otilde; rệt trong năm, kiểu thời tiết điển h&igrave;nh của những tỉnh th&agrave;nh ph&iacute;a Bắc. Tuy nhi&ecirc;n, nơi đ&acirc;y cũng c&oacute; những n&eacute;t ri&ecirc;ng của một tỉnh miền n&uacute;i ven biển. Cụ thể, ở khu vực quần đảo thuộc huyện V&acirc;n Đồn, C&ocirc; T&ocirc;... thời tiết sẽ c&oacute; ch&uacute;t kh&aacute;c biệt. Hơn nữa, Quảng Ninh cũng nằm trong v&ugrave;ng kh&iacute; hậu nhiệt đới n&ecirc;n m&ugrave;a hạ sẽ n&oacute;ng ẩm mưa nhiều, c&ograve;n m&ugrave;a đ&ocirc;ng sẽ lạnh v&agrave; &iacute;t mưa.</p>
<p>Theo kinh nghiệm du lịch Quảng Ninh của nhiều du kh&aacute;ch th&igrave; khoảng từ&nbsp;<strong>cuối th&aacute;ng 4 đến th&aacute;ng 9</strong>&nbsp;ch&iacute;nh l&agrave; thời điểm đẹp nhất để du lịch Quảng Ninh bởi l&uacute;c n&agrave;y biển đẹp, trong xanh, thời tiết m&aacute;t mẻ, trong l&agrave;nh, dễ chịu. Đ&acirc;y cũng l&agrave; khoảng thời gian ở Quảng Ninh diễn ra nhiều hoạt động văn h&oacute;a nổi bật như Tuần lễ du lịch Hạ Long - Quảng Ninh, &acirc;m nhạc m&ugrave;a h&egrave;, lễ hội Y&ecirc;n Tử...</p>
<p><img src="https://statics.vinpearl.com/du-lich-Quang-Ninh-hinh-anh3.jpg" alt="du lich quang ninh hinh anh 3" data-align="center" data-caption="Vịnh Hạ Long từ tr&ecirc;n cao (Nguồn: Foody)" data-entity-type="file" data-entity-uuid="74bd77f7-0b82-4373-b694-c2f110abf100"><em class="img_caption">Vịnh Hạ Long từ tr&ecirc;n cao (Nguồn: Foody)</em></p>', 'Hà Nội', 'Nguyễn Văn A', '14A1-99999', 'Chuyến Quảng Yên - Hà Nội', 200000, 15, 16, 2, 'Sắp khởi hành', 'https://quynhongrouptour.com.vn/wp-content/uploads/2020/03/danh-gia-xe-hyundai-solati.jpg', '2025-06-18', 1, 5, '2025-06-30');
INSERT IGNORE INTO booking_trip.trip (id, address, area, create_at, departure, description, destination, driver, license_plate, name, price, sale, seat, seat_booking, status, thumbnail, update_at, category_id, owner_id, departure_date) VALUES (5, 'số 21, Xã Vũ Oai, Huyện Hoành Bồ, Quảng Ninh', 40, '2025-06-30', 'Quảng Ninh', '<p><strong>Du lịch Quảng Ninh</strong>&nbsp;c&oacute; v&ocirc; v&agrave;n địa điểm đẹp v&agrave; nổi tiếng thu h&uacute;t du kh&aacute;ch bốn phương. Kh&ocirc;ng chỉ c&oacute; vậy, Quảng Ninh c&ograve;n khiến du kh&aacute;ch ngất ng&acirc;y&nbsp;với&nbsp;những đặc sản ngon kh&oacute; cưỡng. Nếu bạn cũng đang c&oacute; dự định đến đ&acirc;y trong thời gian tới th&igrave; h&atilde;y lưu lại ngay c&aacute;c th&ocirc;ng tin ở b&agrave;i viết sau đ&acirc;y nh&eacute;!</p>
<p><img src="https://statics.vinpearl.com/du-lich-Quang-Ninh-hinh-anh1.jpg" alt="du lich quang ninh hinh anh 1" data-align="center" data-caption="Vịnh Hạ Long Quảng Ninh (Nguồn: B&aacute;o Ch&iacute;nh phủ)" data-entity-type="file" data-entity-uuid="5c5e6c07-6294-49a8-97ad-0707ef6dabe5"><em class="img_caption">Vịnh Hạ Long Quảng Ninh (Nguồn: B&aacute;o Ch&iacute;nh phủ)</em></p>
<h2 id="1.+Giới+thiệu+về+du+lịch+Quảng+Ninh+-+V&ugrave;ng+đất+di+sản">1. Giới thiệu về du lịch Quảng Ninh - V&ugrave;ng đất di sản</h2>
<p>Quảng Ninh thuộc v&ugrave;ng Đ&ocirc;ng Bắc Việt Nam. Nơi đ&acirc;y hấp dẫn bởi vẻ đẹp kỳ th&uacute; của n&uacute;i non, s&ocirc;ng nước v&agrave; biển đảo. Nổi bật hơn cả ch&iacute;nh l&agrave;&nbsp;<strong>vịnh Hạ Long - Di sản thi&ecirc;n nhi&ecirc;n thế giới được UNESCO c&ocirc;ng nhận</strong>. Đến với Hạ Long, du kh&aacute;ch sẽ c&oacute; cơ hội chi&ecirc;m ngưỡng bức tranh non nước v&ocirc; c&ugrave;ng ngoạn mục được tạo th&agrave;nh bởi 1.900 h&ograve;n đ&aacute; v&ocirc;i kh&aacute;c nhau c&ugrave;ng nhiều hang động kỳ b&iacute;.</p>
<p>Chưa dừng lại ở đ&oacute;, Quảng Ninh c&ograve;n l&agrave; mảnh đất sở hữu 2 c&ocirc;ng vi&ecirc;n giải tr&iacute; lớn nhất khu vực Đ&ocirc;ng Nam &Aacute; l&agrave; Typhoon Water Park v&agrave; Dragon Park. Tại hai c&ocirc;ng vi&ecirc;n n&agrave;y, c&oacute; rất nhiều những trải nghiệm th&uacute; vị đang chờ đợi du kh&aacute;ch như t&agrave;u lượn si&ecirc;u tốc 1,1km d&agrave;i nhất Ch&acirc;u &Aacute; v&agrave; hơn 12 tr&ograve; chơi dưới nước d&agrave;nh cho mọi lứa tuổi.</p>
<p><img src="https://statics.vinpearl.com/du-lich-Quang-Ninh-hinh-anh2.jpg" alt="du lich quang ninh hinh anh 2" data-align="center" data-caption="Sống ảo khi đi du lịch Quảng Ninh (Nguồn: Vietnammoi)" data-entity-type="file" data-entity-uuid="51e13db7-fb53-4e61-ba2b-624e0038d11c"><em class="img_caption">Sống ảo khi đi du lịch Quảng Ninh (Nguồn: Vietnammoi)</em></p>
<div class="sku-item checked">
<div class="hotel-wrapper promo-wrapper hotel-api">
<div class="hotel-img-wrapper">
<div id="carousel-bacc" class="carousel slide" data-ride="carousel" data-interval="false">
<div class="carousel-inner">
<div class="carousel-item active"><img class="w-100" src="https://booking-static.vinpearl.com/hotels/004a48b7f5de44638f267d5e085f20e8_VPRSHL%20Facade11.jpg" alt="anh khong gian phong" data-src="https://booking-static.vinpearl.com/hotels/004a48b7f5de44638f267d5e085f20e8_VPRSHL Facade11.jpg"></div>
</div>
</div>
</div>
</div>
</div>
<h2 id="2.+N&ecirc;n+đi+du+lịch+ở+Quảng+Ninh+v&agrave;o+thời+gian+n&agrave;o?">2. N&ecirc;n đi du lịch ở Quảng Ninh v&agrave;o thời gian n&agrave;o?</h2>
<p>Quảng Ninh c&oacute; 4 m&ugrave;a r&otilde; rệt trong năm, kiểu thời tiết điển h&igrave;nh của những tỉnh th&agrave;nh ph&iacute;a Bắc. Tuy nhi&ecirc;n, nơi đ&acirc;y cũng c&oacute; những n&eacute;t ri&ecirc;ng của một tỉnh miền n&uacute;i ven biển. Cụ thể, ở khu vực quần đảo thuộc huyện V&acirc;n Đồn, C&ocirc; T&ocirc;... thời tiết sẽ c&oacute; ch&uacute;t kh&aacute;c biệt. Hơn nữa, Quảng Ninh cũng nằm trong v&ugrave;ng kh&iacute; hậu nhiệt đới n&ecirc;n m&ugrave;a hạ sẽ n&oacute;ng ẩm mưa nhiều, c&ograve;n m&ugrave;a đ&ocirc;ng sẽ lạnh v&agrave; &iacute;t mưa.</p>
<p>Theo kinh nghiệm du lịch Quảng Ninh của nhiều du kh&aacute;ch th&igrave; khoảng từ&nbsp;<strong>cuối th&aacute;ng 4 đến th&aacute;ng 9</strong>&nbsp;ch&iacute;nh l&agrave; thời điểm đẹp nhất để du lịch Quảng Ninh bởi l&uacute;c n&agrave;y biển đẹp, trong xanh, thời tiết m&aacute;t mẻ, trong l&agrave;nh, dễ chịu. Đ&acirc;y cũng l&agrave; khoảng thời gian ở Quảng Ninh diễn ra nhiều hoạt động văn h&oacute;a nổi bật như Tuần lễ du lịch Hạ Long - Quảng Ninh, &acirc;m nhạc m&ugrave;a h&egrave;, lễ hội Y&ecirc;n Tử...</p>
<p><img src="https://statics.vinpearl.com/du-lich-Quang-Ninh-hinh-anh3.jpg" alt="du lich quang ninh hinh anh 3" data-align="center" data-caption="Vịnh Hạ Long từ tr&ecirc;n cao (Nguồn: Foody)" data-entity-type="file" data-entity-uuid="74bd77f7-0b82-4373-b694-c2f110abf100"><em class="img_caption">Vịnh Hạ Long từ tr&ecirc;n cao (Nguồn: Foody)</em></p>', 'Hà Nội', 'Nguyễn Văn A', '14A1-99999', 'Chuyến Ba Vàng - Hà Nội', 400000, 15, 4, 2, 'Sắp khởi hành', 'https://www.toyotacanthovn.com/files/new-camry-33-XjGn5Atgfz.jpg', '2025-06-18', 1, 5, '2025-06-30');
INSERT IGNORE INTO booking_trip.trip (id, address, area, create_at, departure, description, destination, driver, license_plate, name, price, sale, seat, seat_booking, status, thumbnail, update_at, category_id, owner_id, departure_date) VALUES (6, 'số 21, Xã Vũ Oai, Huyện Hoành Bồ, Quảng Ninh', 40, '2025-06-30', 'Quảng Ninh', '<p><strong>Du lịch Quảng Ninh</strong>&nbsp;c&oacute; v&ocirc; v&agrave;n địa điểm đẹp v&agrave; nổi tiếng thu h&uacute;t du kh&aacute;ch bốn phương. Kh&ocirc;ng chỉ c&oacute; vậy, Quảng Ninh c&ograve;n khiến du kh&aacute;ch ngất ng&acirc;y&nbsp;với&nbsp;những đặc sản ngon kh&oacute; cưỡng. Nếu bạn cũng đang c&oacute; dự định đến đ&acirc;y trong thời gian tới th&igrave; h&atilde;y lưu lại ngay c&aacute;c th&ocirc;ng tin ở b&agrave;i viết sau đ&acirc;y nh&eacute;!</p>
<p><img src="https://statics.vinpearl.com/du-lich-Quang-Ninh-hinh-anh1.jpg" alt="du lich quang ninh hinh anh 1" data-align="center" data-caption="Vịnh Hạ Long Quảng Ninh (Nguồn: B&aacute;o Ch&iacute;nh phủ)" data-entity-type="file" data-entity-uuid="5c5e6c07-6294-49a8-97ad-0707ef6dabe5"><em class="img_caption">Vịnh Hạ Long Quảng Ninh (Nguồn: B&aacute;o Ch&iacute;nh phủ)</em></p>
<h2 id="1.+Giới+thiệu+về+du+lịch+Quảng+Ninh+-+V&ugrave;ng+đất+di+sản">1. Giới thiệu về du lịch Quảng Ninh - V&ugrave;ng đất di sản</h2>
<p>Quảng Ninh thuộc v&ugrave;ng Đ&ocirc;ng Bắc Việt Nam. Nơi đ&acirc;y hấp dẫn bởi vẻ đẹp kỳ th&uacute; của n&uacute;i non, s&ocirc;ng nước v&agrave; biển đảo. Nổi bật hơn cả ch&iacute;nh l&agrave;&nbsp;<strong>vịnh Hạ Long - Di sản thi&ecirc;n nhi&ecirc;n thế giới được UNESCO c&ocirc;ng nhận</strong>. Đến với Hạ Long, du kh&aacute;ch sẽ c&oacute; cơ hội chi&ecirc;m ngưỡng bức tranh non nước v&ocirc; c&ugrave;ng ngoạn mục được tạo th&agrave;nh bởi 1.900 h&ograve;n đ&aacute; v&ocirc;i kh&aacute;c nhau c&ugrave;ng nhiều hang động kỳ b&iacute;.</p>
<p>Chưa dừng lại ở đ&oacute;, Quảng Ninh c&ograve;n l&agrave; mảnh đất sở hữu 2 c&ocirc;ng vi&ecirc;n giải tr&iacute; lớn nhất khu vực Đ&ocirc;ng Nam &Aacute; l&agrave; Typhoon Water Park v&agrave; Dragon Park. Tại hai c&ocirc;ng vi&ecirc;n n&agrave;y, c&oacute; rất nhiều những trải nghiệm th&uacute; vị đang chờ đợi du kh&aacute;ch như t&agrave;u lượn si&ecirc;u tốc 1,1km d&agrave;i nhất Ch&acirc;u &Aacute; v&agrave; hơn 12 tr&ograve; chơi dưới nước d&agrave;nh cho mọi lứa tuổi.</p>
<p><img src="https://statics.vinpearl.com/du-lich-Quang-Ninh-hinh-anh2.jpg" alt="du lich quang ninh hinh anh 2" data-align="center" data-caption="Sống ảo khi đi du lịch Quảng Ninh (Nguồn: Vietnammoi)" data-entity-type="file" data-entity-uuid="51e13db7-fb53-4e61-ba2b-624e0038d11c"><em class="img_caption">Sống ảo khi đi du lịch Quảng Ninh (Nguồn: Vietnammoi)</em></p>
<div class="sku-item checked">
<div class="hotel-wrapper promo-wrapper hotel-api">
<div class="hotel-img-wrapper">
<div id="carousel-bacc" class="carousel slide" data-ride="carousel" data-interval="false">
<div class="carousel-inner">
<div class="carousel-item active"><img class="w-100" src="https://booking-static.vinpearl.com/hotels/004a48b7f5de44638f267d5e085f20e8_VPRSHL%20Facade11.jpg" alt="anh khong gian phong" data-src="https://booking-static.vinpearl.com/hotels/004a48b7f5de44638f267d5e085f20e8_VPRSHL Facade11.jpg"></div>
</div>
</div>
</div>
</div>
</div>
<h2 id="2.+N&ecirc;n+đi+du+lịch+ở+Quảng+Ninh+v&agrave;o+thời+gian+n&agrave;o?">2. N&ecirc;n đi du lịch ở Quảng Ninh v&agrave;o thời gian n&agrave;o?</h2>
<p>Quảng Ninh c&oacute; 4 m&ugrave;a r&otilde; rệt trong năm, kiểu thời tiết điển h&igrave;nh của những tỉnh th&agrave;nh ph&iacute;a Bắc. Tuy nhi&ecirc;n, nơi đ&acirc;y cũng c&oacute; những n&eacute;t ri&ecirc;ng của một tỉnh miền n&uacute;i ven biển. Cụ thể, ở khu vực quần đảo thuộc huyện V&acirc;n Đồn, C&ocirc; T&ocirc;... thời tiết sẽ c&oacute; ch&uacute;t kh&aacute;c biệt. Hơn nữa, Quảng Ninh cũng nằm trong v&ugrave;ng kh&iacute; hậu nhiệt đới n&ecirc;n m&ugrave;a hạ sẽ n&oacute;ng ẩm mưa nhiều, c&ograve;n m&ugrave;a đ&ocirc;ng sẽ lạnh v&agrave; &iacute;t mưa.</p>
<p>Theo kinh nghiệm du lịch Quảng Ninh của nhiều du kh&aacute;ch th&igrave; khoảng từ&nbsp;<strong>cuối th&aacute;ng 4 đến th&aacute;ng 9</strong>&nbsp;ch&iacute;nh l&agrave; thời điểm đẹp nhất để du lịch Quảng Ninh bởi l&uacute;c n&agrave;y biển đẹp, trong xanh, thời tiết m&aacute;t mẻ, trong l&agrave;nh, dễ chịu. Đ&acirc;y cũng l&agrave; khoảng thời gian ở Quảng Ninh diễn ra nhiều hoạt động văn h&oacute;a nổi bật như Tuần lễ du lịch Hạ Long - Quảng Ninh, &acirc;m nhạc m&ugrave;a h&egrave;, lễ hội Y&ecirc;n Tử...</p>
<p><img src="https://statics.vinpearl.com/du-lich-Quang-Ninh-hinh-anh3.jpg" alt="du lich quang ninh hinh anh 3" data-align="center" data-caption="Vịnh Hạ Long từ tr&ecirc;n cao (Nguồn: Foody)" data-entity-type="file" data-entity-uuid="74bd77f7-0b82-4373-b694-c2f110abf100"><em class="img_caption">Vịnh Hạ Long từ tr&ecirc;n cao (Nguồn: Foody)</em></p>', 'Hà Nội', 'Nguyễn Văn A', '14A1-99999', 'Chuyến Uông Bí - Hà Nội', 100000, 15, 10, 2, 'Sắp khởi hành', 'https://giaxeoto24h.vn/wp-content/uploads/2025/03/ford-transit-Limousine.jpg', '2025-06-18', 1, 5, '2025-06-30');
INSERT IGNORE INTO booking_trip.trip (id, address, area, create_at, departure, description, destination, driver, license_plate, name, price, sale, seat, seat_booking, status, thumbnail, update_at, category_id, owner_id, departure_date) VALUES (8, 'số 21, Xã Vũ Oai, Huyện Hoành Bồ, Quảng Ninh', 40, '2025-06-30', 'Quảng Ninh', '<p><strong>Du lịch Quảng Ninh</strong>&nbsp;c&oacute; v&ocirc; v&agrave;n địa điểm đẹp v&agrave; nổi tiếng thu h&uacute;t du kh&aacute;ch bốn phương. Kh&ocirc;ng chỉ c&oacute; vậy, Quảng Ninh c&ograve;n khiến du kh&aacute;ch ngất ng&acirc;y&nbsp;với&nbsp;những đặc sản ngon kh&oacute; cưỡng. Nếu bạn cũng đang c&oacute; dự định đến đ&acirc;y trong thời gian tới th&igrave; h&atilde;y lưu lại ngay c&aacute;c th&ocirc;ng tin ở b&agrave;i viết sau đ&acirc;y nh&eacute;!</p>
<p><img src="https://statics.vinpearl.com/du-lich-Quang-Ninh-hinh-anh1.jpg" alt="du lich quang ninh hinh anh 1" data-align="center" data-caption="Vịnh Hạ Long Quảng Ninh (Nguồn: B&aacute;o Ch&iacute;nh phủ)" data-entity-type="file" data-entity-uuid="5c5e6c07-6294-49a8-97ad-0707ef6dabe5"><em class="img_caption">Vịnh Hạ Long Quảng Ninh (Nguồn: B&aacute;o Ch&iacute;nh phủ)</em></p>
<h2 id="1.+Giới+thiệu+về+du+lịch+Quảng+Ninh+-+V&ugrave;ng+đất+di+sản">1. Giới thiệu về du lịch Quảng Ninh - V&ugrave;ng đất di sản</h2>
<p>Quảng Ninh thuộc v&ugrave;ng Đ&ocirc;ng Bắc Việt Nam. Nơi đ&acirc;y hấp dẫn bởi vẻ đẹp kỳ th&uacute; của n&uacute;i non, s&ocirc;ng nước v&agrave; biển đảo. Nổi bật hơn cả ch&iacute;nh l&agrave;&nbsp;<strong>vịnh Hạ Long - Di sản thi&ecirc;n nhi&ecirc;n thế giới được UNESCO c&ocirc;ng nhận</strong>. Đến với Hạ Long, du kh&aacute;ch sẽ c&oacute; cơ hội chi&ecirc;m ngưỡng bức tranh non nước v&ocirc; c&ugrave;ng ngoạn mục được tạo th&agrave;nh bởi 1.900 h&ograve;n đ&aacute; v&ocirc;i kh&aacute;c nhau c&ugrave;ng nhiều hang động kỳ b&iacute;.</p>
<p>Chưa dừng lại ở đ&oacute;, Quảng Ninh c&ograve;n l&agrave; mảnh đất sở hữu 2 c&ocirc;ng vi&ecirc;n giải tr&iacute; lớn nhất khu vực Đ&ocirc;ng Nam &Aacute; l&agrave; Typhoon Water Park v&agrave; Dragon Park. Tại hai c&ocirc;ng vi&ecirc;n n&agrave;y, c&oacute; rất nhiều những trải nghiệm th&uacute; vị đang chờ đợi du kh&aacute;ch như t&agrave;u lượn si&ecirc;u tốc 1,1km d&agrave;i nhất Ch&acirc;u &Aacute; v&agrave; hơn 12 tr&ograve; chơi dưới nước d&agrave;nh cho mọi lứa tuổi.</p>
<p><img src="https://statics.vinpearl.com/du-lich-Quang-Ninh-hinh-anh2.jpg" alt="du lich quang ninh hinh anh 2" data-align="center" data-caption="Sống ảo khi đi du lịch Quảng Ninh (Nguồn: Vietnammoi)" data-entity-type="file" data-entity-uuid="51e13db7-fb53-4e61-ba2b-624e0038d11c"><em class="img_caption">Sống ảo khi đi du lịch Quảng Ninh (Nguồn: Vietnammoi)</em></p>
<div class="sku-item checked">
<div class="hotel-wrapper promo-wrapper hotel-api">
<div class="hotel-img-wrapper">
<div id="carousel-bacc" class="carousel slide" data-ride="carousel" data-interval="false">
<div class="carousel-inner">
<div class="carousel-item active"><img class="w-100" src="https://booking-static.vinpearl.com/hotels/004a48b7f5de44638f267d5e085f20e8_VPRSHL%20Facade11.jpg" alt="anh khong gian phong" data-src="https://booking-static.vinpearl.com/hotels/004a48b7f5de44638f267d5e085f20e8_VPRSHL Facade11.jpg"></div>
</div>
</div>
</div>
</div>
</div>
<h2 id="2.+N&ecirc;n+đi+du+lịch+ở+Quảng+Ninh+v&agrave;o+thời+gian+n&agrave;o?">2. N&ecirc;n đi du lịch ở Quảng Ninh v&agrave;o thời gian n&agrave;o?</h2>
<p>Quảng Ninh c&oacute; 4 m&ugrave;a r&otilde; rệt trong năm, kiểu thời tiết điển h&igrave;nh của những tỉnh th&agrave;nh ph&iacute;a Bắc. Tuy nhi&ecirc;n, nơi đ&acirc;y cũng c&oacute; những n&eacute;t ri&ecirc;ng của một tỉnh miền n&uacute;i ven biển. Cụ thể, ở khu vực quần đảo thuộc huyện V&acirc;n Đồn, C&ocirc; T&ocirc;... thời tiết sẽ c&oacute; ch&uacute;t kh&aacute;c biệt. Hơn nữa, Quảng Ninh cũng nằm trong v&ugrave;ng kh&iacute; hậu nhiệt đới n&ecirc;n m&ugrave;a hạ sẽ n&oacute;ng ẩm mưa nhiều, c&ograve;n m&ugrave;a đ&ocirc;ng sẽ lạnh v&agrave; &iacute;t mưa.</p>
<p>Theo kinh nghiệm du lịch Quảng Ninh của nhiều du kh&aacute;ch th&igrave; khoảng từ&nbsp;<strong>cuối th&aacute;ng 4 đến th&aacute;ng 9</strong>&nbsp;ch&iacute;nh l&agrave; thời điểm đẹp nhất để du lịch Quảng Ninh bởi l&uacute;c n&agrave;y biển đẹp, trong xanh, thời tiết m&aacute;t mẻ, trong l&agrave;nh, dễ chịu. Đ&acirc;y cũng l&agrave; khoảng thời gian ở Quảng Ninh diễn ra nhiều hoạt động văn h&oacute;a nổi bật như Tuần lễ du lịch Hạ Long - Quảng Ninh, &acirc;m nhạc m&ugrave;a h&egrave;, lễ hội Y&ecirc;n Tử...</p>
<p><img src="https://statics.vinpearl.com/du-lich-Quang-Ninh-hinh-anh3.jpg" alt="du lich quang ninh hinh anh 3" data-align="center" data-caption="Vịnh Hạ Long từ tr&ecirc;n cao (Nguồn: Foody)" data-entity-type="file" data-entity-uuid="74bd77f7-0b82-4373-b694-c2f110abf100"><em class="img_caption">Vịnh Hạ Long từ tr&ecirc;n cao (Nguồn: Foody)</em></p>', 'Hà Nội', 'Nguyễn Văn A', '14A1-99999', 'Chuyến Đông Triều - Hà Nội', 200000, 20, 24, 0, 'Sắp khởi hành', 'https://thuexeviet.vn/wp-content/uploads/2023/09/thue%CC%82-xe-du-li%CC%A3ch-24-cho%CC%82%CC%83-1024x768.jpg', '2025-06-18', 2, 5, '2025-06-30');
INSERT IGNORE INTO booking_trip.trip (id, address, area, create_at, departure, description, destination, driver, license_plate, name, price, sale, seat, seat_booking, status, thumbnail, update_at, category_id, owner_id, departure_date) VALUES (9, 'số 21, Xã Vũ Oai, Huyện Hoành Bồ, Quảng Ninh', 40, '2025-06-30', 'Quảng Ninh', '<p><strong>Du lịch Quảng Ninh</strong>&nbsp;c&oacute; v&ocirc; v&agrave;n địa điểm đẹp v&agrave; nổi tiếng thu h&uacute;t du kh&aacute;ch bốn phương. Kh&ocirc;ng chỉ c&oacute; vậy, Quảng Ninh c&ograve;n khiến du kh&aacute;ch ngất ng&acirc;y&nbsp;với&nbsp;những đặc sản ngon kh&oacute; cưỡng. Nếu bạn cũng đang c&oacute; dự định đến đ&acirc;y trong thời gian tới th&igrave; h&atilde;y lưu lại ngay c&aacute;c th&ocirc;ng tin ở b&agrave;i viết sau đ&acirc;y nh&eacute;!</p>
<p><img src="https://statics.vinpearl.com/du-lich-Quang-Ninh-hinh-anh1.jpg" alt="du lich quang ninh hinh anh 1" data-align="center" data-caption="Vịnh Hạ Long Quảng Ninh (Nguồn: B&aacute;o Ch&iacute;nh phủ)" data-entity-type="file" data-entity-uuid="5c5e6c07-6294-49a8-97ad-0707ef6dabe5"><em class="img_caption">Vịnh Hạ Long Quảng Ninh (Nguồn: B&aacute;o Ch&iacute;nh phủ)</em></p>
<h2 id="1.+Giới+thiệu+về+du+lịch+Quảng+Ninh+-+V&ugrave;ng+đất+di+sản">1. Giới thiệu về du lịch Quảng Ninh - V&ugrave;ng đất di sản</h2>
<p>Quảng Ninh thuộc v&ugrave;ng Đ&ocirc;ng Bắc Việt Nam. Nơi đ&acirc;y hấp dẫn bởi vẻ đẹp kỳ th&uacute; của n&uacute;i non, s&ocirc;ng nước v&agrave; biển đảo. Nổi bật hơn cả ch&iacute;nh l&agrave;&nbsp;<strong>vịnh Hạ Long - Di sản thi&ecirc;n nhi&ecirc;n thế giới được UNESCO c&ocirc;ng nhận</strong>. Đến với Hạ Long, du kh&aacute;ch sẽ c&oacute; cơ hội chi&ecirc;m ngưỡng bức tranh non nước v&ocirc; c&ugrave;ng ngoạn mục được tạo th&agrave;nh bởi 1.900 h&ograve;n đ&aacute; v&ocirc;i kh&aacute;c nhau c&ugrave;ng nhiều hang động kỳ b&iacute;.</p>
<p>Chưa dừng lại ở đ&oacute;, Quảng Ninh c&ograve;n l&agrave; mảnh đất sở hữu 2 c&ocirc;ng vi&ecirc;n giải tr&iacute; lớn nhất khu vực Đ&ocirc;ng Nam &Aacute; l&agrave; Typhoon Water Park v&agrave; Dragon Park. Tại hai c&ocirc;ng vi&ecirc;n n&agrave;y, c&oacute; rất nhiều những trải nghiệm th&uacute; vị đang chờ đợi du kh&aacute;ch như t&agrave;u lượn si&ecirc;u tốc 1,1km d&agrave;i nhất Ch&acirc;u &Aacute; v&agrave; hơn 12 tr&ograve; chơi dưới nước d&agrave;nh cho mọi lứa tuổi.</p>
<p><img src="https://statics.vinpearl.com/du-lich-Quang-Ninh-hinh-anh2.jpg" alt="du lich quang ninh hinh anh 2" data-align="center" data-caption="Sống ảo khi đi du lịch Quảng Ninh (Nguồn: Vietnammoi)" data-entity-type="file" data-entity-uuid="51e13db7-fb53-4e61-ba2b-624e0038d11c"><em class="img_caption">Sống ảo khi đi du lịch Quảng Ninh (Nguồn: Vietnammoi)</em></p>
<div class="sku-item checked">
<div class="hotel-wrapper promo-wrapper hotel-api">
<div class="hotel-img-wrapper">
<div id="carousel-bacc" class="carousel slide" data-ride="carousel" data-interval="false">
<div class="carousel-inner">
<div class="carousel-item active"><img class="w-100" src="https://booking-static.vinpearl.com/hotels/004a48b7f5de44638f267d5e085f20e8_VPRSHL%20Facade11.jpg" alt="anh khong gian phong" data-src="https://booking-static.vinpearl.com/hotels/004a48b7f5de44638f267d5e085f20e8_VPRSHL Facade11.jpg"></div>
</div>
</div>
</div>
</div>
</div>
<h2 id="2.+N&ecirc;n+đi+du+lịch+ở+Quảng+Ninh+v&agrave;o+thời+gian+n&agrave;o?">2. N&ecirc;n đi du lịch ở Quảng Ninh v&agrave;o thời gian n&agrave;o?</h2>
<p>Quảng Ninh c&oacute; 4 m&ugrave;a r&otilde; rệt trong năm, kiểu thời tiết điển h&igrave;nh của những tỉnh th&agrave;nh ph&iacute;a Bắc. Tuy nhi&ecirc;n, nơi đ&acirc;y cũng c&oacute; những n&eacute;t ri&ecirc;ng của một tỉnh miền n&uacute;i ven biển. Cụ thể, ở khu vực quần đảo thuộc huyện V&acirc;n Đồn, C&ocirc; T&ocirc;... thời tiết sẽ c&oacute; ch&uacute;t kh&aacute;c biệt. Hơn nữa, Quảng Ninh cũng nằm trong v&ugrave;ng kh&iacute; hậu nhiệt đới n&ecirc;n m&ugrave;a hạ sẽ n&oacute;ng ẩm mưa nhiều, c&ograve;n m&ugrave;a đ&ocirc;ng sẽ lạnh v&agrave; &iacute;t mưa.</p>
<p>Theo kinh nghiệm du lịch Quảng Ninh của nhiều du kh&aacute;ch th&igrave; khoảng từ&nbsp;<strong>cuối th&aacute;ng 4 đến th&aacute;ng 9</strong>&nbsp;ch&iacute;nh l&agrave; thời điểm đẹp nhất để du lịch Quảng Ninh bởi l&uacute;c n&agrave;y biển đẹp, trong xanh, thời tiết m&aacute;t mẻ, trong l&agrave;nh, dễ chịu. Đ&acirc;y cũng l&agrave; khoảng thời gian ở Quảng Ninh diễn ra nhiều hoạt động văn h&oacute;a nổi bật như Tuần lễ du lịch Hạ Long - Quảng Ninh, &acirc;m nhạc m&ugrave;a h&egrave;, lễ hội Y&ecirc;n Tử...</p>
<p><img src="https://statics.vinpearl.com/du-lich-Quang-Ninh-hinh-anh3.jpg" alt="du lich quang ninh hinh anh 3" data-align="center" data-caption="Vịnh Hạ Long từ tr&ecirc;n cao (Nguồn: Foody)" data-entity-type="file" data-entity-uuid="74bd77f7-0b82-4373-b694-c2f110abf100"><em class="img_caption">Vịnh Hạ Long từ tr&ecirc;n cao (Nguồn: Foody)</em></p>', 'Hà Nội', 'Nguyễn Văn A', '14A1-99999', 'Chuyến Tuần Châu - Hà Nội', 200000, 1, 24, 0, 'Sắp khởi hành', 'https://thuexeviet.vn/wp-content/uploads/2023/09/thue%CC%82-xe-24-cho%CC%82%CC%83-hcm-1024x768.jpg', '2025-06-18', 2, 5, '2025-06-30');


